

#   INTRO PAGE
#   PUSH START BUTTON
#   1 PLAYER ONLY
#   BONUS PAC-MAN FOR 100000

#   RECICLA ANIMAZIONE IN INSTRUCTION
#   MA QUESTA VOLTA PACMAN VINE
#   RINCORSO E SPARISCE DALLO SCHERMO

#   Created for 42 Pac-Man project
