"""Game specifications."""

# ===========================================================================
#   Chapter IV - Game specifications
# ===========================================================================
#   VI.1 Level structure
# ---------------------------------------------------------------------------
# • A maze with walls and corridors, generated by the assigned
#   A-Maze-ing package.
# • The first level is composed of a maze generated with a fixed seed
#   (e.g., 42), then, each subsequent level is composed of a maze
#   randomly generated.
# • Pacgums (small dots) in most corridors.
# • Super-pacgums (power pellets) in the 4 corners of the maze.
# • 4 ghosts, one in each corner of the maze.
# • The player starts in the middle of the maze

# COSTRUISCI LV N ==========================================================
# 1. Adattarsi all'interfaccia di A-Maze-ing per ottenere la geometria grezza
# muri e corridoi. Questa parte è vincolata dal V.4: non puoi modificare il
# pacchetto, il tuo loader si adatta a lui. È puro "adapter pattern": traduci
# l'output del pacchetto esterno in una struttura che il resto del tuo gioco
# capisce.
#
# 2 Applicare le regole di popolamento specifiche di Pac-Man sopra quella
# geometria: dove vanno i pacgum (nella maggior parte dei corridoi — non
# tutti, quindi c'è una regola di distribuzione da decidere), dove i 4
# super-pacgum (angoli), dove i 4 fantasmi (angoli), dove il player (centro).
